name: OpenAPI

on:
  push:
    paths:
      - 'core-api/rest/**'
      - '.github/workflows/openapi.yml'
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'core-api/rest/**'
      - '.github/workflows/openapi.yml'

jobs:
  validate:
    name: Validate OpenAPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Validate
        uses: mbowman100/swagger-validator-action@master
        with:
          files: |
            ./core-api/rest/UCR2-openapi.yaml
