name: OpenAPI

on:
  push:
    paths:
      - 'core-api/rest/**'
      - '.github/workflows/openapi.yml'
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'core-api/rest/**'
      - '.github/workflows/openapi.yml'

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false
jobs:
  validate:
    name: Validate OpenAPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Validate
        uses: mbowman100/swagger-validator-action@master
        with:
          files: |
            ./core-api/rest/UCR-core-openapi.yaml

  publish:
    name: Publish GitHub pages
    runs-on: ubuntu-latest
    needs: [ validate ]
    steps:
      - name: prepare GH page deployment
        run: |
          cp ./core-api/rest/UCR-core-openapi.yaml ./core-api/rest/swagger-ui
      - name: Deploy core API GH page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./core-api/rest/swagger-ui
          target-folder: ./rest
